### PR TITLE
Use Explicit Atomics In The Internal Spinlock

### LINKED ISSUE #190: Inadequate Atomic Guarantees In QTHREAD_FASTLOCK_LOCK
`QTHREAD_FASTLOCK_LOCK` and the related functions need to be rewritten to use atomic reads and writes instead of relying on the atomicity guarantees from x86. For example, there's currently a race condition between
https://github.com/sandialabs/qthreads/blob/d6ce514a70c65b74c5e04906615ec51c7f288e0f/src/feb.c#L986 and https://github.com/sandialabs/qthreads/blob/d6ce514a70c65b74c5e04906615ec51c7f288e0f/src/qthread.c#L652.

Note: this shows up readily in the hello_world_multi test.

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Fixes #190.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Still tracking some unusual bugs that are likely related to this so I'm converting it to a draft for now.

**Comment by insertinterestingnamehere** [comment]
Okay, it looks like the other issues were resolved by other patches at this point. This one's good to go too. @janciesko can you review this one when you get a minute?

**Comment by insertinterestingnamehere** [comment]
Throwing in a small fix for an intermittent race condition in this same section of code since it wouldn't make any sense without the context of this patch too.

**Review by janciesko — APPROVED** [review]
LGTM

**Pull request merged**
