### PR TITLE
Fix Undefined Behavior Sanitizer Errors

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Depends on both https://github.com/sandialabs/qthreads/pull/181 and https://github.com/sandialabs/qthreads/pull/170. I'll revise it to not depend on those if that ends up being possible after debugging.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Okay, this one is ready to go too. I don't want to try to untangle it from #170 and #181 though, so those need to be reviewed/merged first.

**Comment by janciesko** [comment]
Great, maybe rebase this once #170 is in so I see only the new stuff.

**Comment by insertinterestingnamehere** [comment]
Rebased. Thanks!

**Review by janciesko — APPROVED** [review]
LGTM

**Pull request merged**
