### PR TITLE
Add html man pages

### PR DESCRIPTION
**Pull request by janciesko**
This adds generated html man files making quick API lookup more convenient.

### CODE REVIEW

**Comment by olivier-snl** [comment]
> @olivier-snl Ping

Do these get installed in share along with the existing man pages?  Does this make [htmlize.sh](https://github.com/Qthreads/qthreads/blob/main/man/htmlize.sh) obsolete, and subject to removal?

**Comment by janciesko** [comment]
I think we could leave the gen script. The html files do not install - that's a good point. I'll include them in the make install  step.

**Comment by janciesko** [comment]
For some reason, ./configure does not generate the code for the install target. make install currently does not place the html directory into $(prefix)/man/. I do not know why.

**Comment by insertinterestingnamehere** [comment]
Do we necessarily want to include generated files directly in the git repo?

**Pull request closed without merging**
